### ISSUE TITLE
HTTP multipart batch spec

### ISSUE THREAD

**Issue by tamlyn** [debitoor/multifetch#6]
Would it be possible to add support for [HTTP Multipart Batched Request Format](https://tools.ietf.org/id/draft-snell-http-batch-00.html)? That would make this module compatible with [jonsamwell/angular-http-batcher](https://github.com/jonsamwell/angular-http-batcher) which would benefit MEAN developers everywhere.

**Comment by bubenshchykov** [comment]
Hi, nice suggestion, but that would require a complete module rewrite. Currently it's designed to handle GET requests with a simple query-driven api, but efficient use of streams behind the scene.

multipart/mixed definitely worth a new module. Please try to ask community at stackoverflow or so, maybe someone has it already.
